FROM node:20-alpine AS build
WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm -F @scis/shared build
RUN pnpm -F @scis/student-web build

FROM nginx:1.27-alpine
COPY infra/nginx.student.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/packages/student-web/dist /usr/share/nginx/html
EXPOSE 80
