services:
  - type: web
    name: scis-backend
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm -F @scis/backend build && pnpm -F @scis/backend prisma generate
    startCommand: node -r dotenv/config packages/backend/dist/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: INGEST_SERVICE_TOKEN
        sync: false
    autoDeploy: true
